#ifndef TRANSPORT_RECORDER_EVENT_EXPORT_FORMAT_H
#define TRANSPORT_RECORDER_EVENT_EXPORT_FORMAT_H

#define EVENT_EXPORT_VERSION 3U
#define EVENT_EXPORT_HEADER_SIZE 160U
#define EVENT_EXPORT_SAMPLE_SIZE 16U
#define EVENT_EXPORT_SAMPLE_RATE_HZ 1600U

#define EVENT_EXPORT_CONTEXT_UTC_VALID (1U << 0)
#define EVENT_EXPORT_CONTEXT_ENVIRONMENT_VALID (1U << 1)
#define EVENT_EXPORT_CONTEXT_ENVIRONMENT_FRESH (1U << 2)
#define EVENT_EXPORT_CONTEXT_LSE_RUNNING (1U << 3)
#define EVENT_EXPORT_CONTEXT_STORAGE_READY (1U << 4)
#define EVENT_EXPORT_CONTEXT_POWER_KNOWN (1U << 5)
#define EVENT_EXPORT_CONTEXT_STACK_WATERMARK_AVAILABLE (1U << 6)
#define EVENT_EXPORT_CONTEXT_DEFINED_MASK \
    (EVENT_EXPORT_CONTEXT_UTC_VALID \
     | EVENT_EXPORT_CONTEXT_ENVIRONMENT_VALID \
     | EVENT_EXPORT_CONTEXT_ENVIRONMENT_FRESH \
     | EVENT_EXPORT_CONTEXT_LSE_RUNNING \
     | EVENT_EXPORT_CONTEXT_STORAGE_READY \
     | EVENT_EXPORT_CONTEXT_POWER_KNOWN \
     | EVENT_EXPORT_CONTEXT_STACK_WATERMARK_AVAILABLE)

#endif
