#ifndef TRANSPORT_RECORDER_EVENT_LOG_FORMAT_H
#define TRANSPORT_RECORDER_EVENT_LOG_FORMAT_H

#include <stdint.h>

#define EVENT_LOG_FORMAT_VERSION 1U
#define EVENT_LOG_ERASE_SECTOR_BYTES 4096U
#define EVENT_LOG_SUPERBLOCK_A_OFFSET 0U
#define EVENT_LOG_SUPERBLOCK_B_OFFSET EVENT_LOG_ERASE_SECTOR_BYTES
#define EVENT_LOG_DATA_OFFSET (2U * EVENT_LOG_ERASE_SECTOR_BYTES)
#define EVENT_LOG_SUPERBLOCK_HEADER_BYTES 32U
#define EVENT_LOG_RECORD_HEADER_BYTES 32U
#define EVENT_LOG_RECORD_FOOTER_BYTES 16U
#define EVENT_LOG_COMMIT_ERASED UINT32_C(0xFFFFFFFF)
#define EVENT_LOG_COMMIT_VALID UINT32_C(0x00000000)
#define EVENT_LOG_CHECKPOINT_INTERVAL 16U

#endif
