from building import DefineGroup, GetCurrentDir


current_dir = GetCurrentDir()
group = DefineGroup(
    "Storage",
    ["event_log.c", "nor_flash_w25q.c"],
    depend=[""],
    CPPPATH=[current_dir],
    LOCAL_CFLAGS=" -Wall -Wextra",
)

Return("group")
