"""Generate TERP message IDs for C and Python from terp_messages.yaml."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPOSITORY_ROOT / "protocol" / "terp_messages.yaml"
C_OUTPUT = REPOSITORY_ROOT / "firmware" / "components" / "protocol" / "terp_messages_generated.h"
PYTHON_OUTPUT = REPOSITORY_ROOT / "host" / "transport_recorder" / "protocol" / "messages_generated.py"
ENTRY = re.compile(r"^  - id: (0x[0-9A-F]+)\r?$\n^    name: ([A-Z_]+)\r?$", re.MULTILINE)


def load_messages() -> list[tuple[str, int]]:
    messages = [(name, int(identifier, 16)) for identifier, name in ENTRY.findall(
        SOURCE.read_text(encoding="utf-8")
    )]
    if not messages or len({name for name, _ in messages}) != len(messages):
        raise ValueError("terp_messages.yaml contains missing or duplicate names")
    if len({identifier for _, identifier in messages}) != len(messages):
        raise ValueError("terp_messages.yaml contains duplicate IDs")
    return messages


def render_c(messages: list[tuple[str, int]]) -> str:
    defines = "\n".join(
        f"#define TERP_MESSAGE_{name} UINT16_C(0x{identifier:04X})"
        for name, identifier in messages
    )
    return (
        "/* Generated by protocol/generate_messages.py; do not edit. */\n"
        "#ifndef TRANSPORT_RECORDER_TERP_MESSAGES_GENERATED_H\n"
        "#define TRANSPORT_RECORDER_TERP_MESSAGES_GENERATED_H\n\n"
        "#include <stdint.h>\n\n"
        f"{defines}\n\n"
        "#endif\n"
    )


def render_python(messages: list[tuple[str, int]]) -> str:
    members = "\n".join(f"    {name} = 0x{identifier:04X}" for name, identifier in messages)
    return (
        "\"\"\"Generated by protocol/generate_messages.py; do not edit.\"\"\"\n\n"
        "from enum import IntEnum\n\n\n"
        "class MessageType(IntEnum):\n"
        f"{members}\n"
    )


def update(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    messages = load_messages()
    current = [
        update(C_OUTPUT, render_c(messages), args.check),
        update(PYTHON_OUTPUT, render_python(messages), args.check),
    ]
    if not all(current):
        raise SystemExit("generated TERP message files are stale")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
