#ifndef TRANSPORT_RECORDER_BUILD_IDENTITY_H
#define TRANSPORT_RECORDER_BUILD_IDENTITY_H

#ifndef TRANSPORT_BUILD_PROFILE
#define TRANSPORT_BUILD_PROFILE "debug"
#endif

#ifndef TRANSPORT_GIT_REVISION
#define TRANSPORT_GIT_REVISION "local"
#endif

#ifndef TRANSPORT_DEVICE_SERIAL
#define TRANSPORT_DEVICE_SERIAL "pending"
#endif

#endif
