#ifndef TRANSPORT_RECORDER_BOOTLOADER_QSPI_PROFILE_H
#define TRANSPORT_RECORDER_BOOTLOADER_QSPI_PROFILE_H

#include <stdbool.h>
#include <stdint.h>

#define BOOTLOADER_QSPI_EXPECTED_JEDEC UINT32_C(0xEF4017)
#define BOOTLOADER_QSPI_FLASH_SIZE 22U
#define BOOTLOADER_QSPI_MAX_CLOCK_HZ UINT32_C(40000000)
#define BOOTLOADER_QSPI_SOURCE_CLOCK_HZ UINT32_C(240000000)
#define BOOTLOADER_QSPI_CLOCK_PRESCALER \
    ((BOOTLOADER_QSPI_SOURCE_CLOCK_HZ / BOOTLOADER_QSPI_MAX_CLOCK_HZ) - 1U)
#define BOOTLOADER_QSPI_ADDRESS_BITS 24U
#define BOOTLOADER_QSPI_PAGE_BYTES UINT32_C(256)
#define BOOTLOADER_QSPI_ERASE_BYTES UINT32_C(4096)
#define BOOTLOADER_QSPI_READ_COMMAND 0x03U
#define BOOTLOADER_QSPI_PROGRAM_COMMAND 0x02U
#define BOOTLOADER_QSPI_ERASE_COMMAND 0x20U

bool bootloader_qspi_profile_is_expected_jedec(uint32_t jedec_id);

#endif
