#ifndef TRANSPORT_RECORDER_BOARD_PINMAP_H
#define TRANSPORT_RECORDER_BOARD_PINMAP_H

#include <stdint.h>

#define BOARD_LED_GPIO_PORT GPIOE
#define BOARD_LED_GPIO_PIN GPIO_PIN_3
#define BOARD_LED_ACTIVE_HIGH 1

#define BOARD_BUTTON_GPIO_PORT GPIOC
#define BOARD_BUTTON_GPIO_PIN GPIO_PIN_13
#define BOARD_BUTTON_ACTIVE_HIGH 1

#define BOARD_USART1_TX_GPIO_PORT GPIOA
#define BOARD_USART1_TX_GPIO_PIN GPIO_PIN_9
#define BOARD_USART1_RX_GPIO_PORT GPIOA
#define BOARD_USART1_RX_GPIO_PIN GPIO_PIN_10
#define BOARD_USART1_GPIO_AF GPIO_AF7_USART1

/* USART3 is reserved for the TERP byte transport, separate from FinSH UART1. */
#define BOARD_USART3_TX_GPIO_PORT GPIOB
#define BOARD_USART3_TX_GPIO_PIN GPIO_PIN_10
#define BOARD_USART3_RX_GPIO_PORT GPIOB
#define BOARD_USART3_RX_GPIO_PIN GPIO_PIN_11
#define BOARD_USART3_GPIO_AF GPIO_AF7_USART3

#define BOARD_HSE_FREQUENCY_HZ UINT32_C(25000000)
#define BOARD_LSE_FREQUENCY_HZ UINT32_C(32768)
#define BOARD_HSE_OSCILLATOR_PRESENT 1
#define BOARD_LSE_OSCILLATOR_PRESENT 1
#define BOARD_SWD_INTERFACE_ENABLED 1

/*
 * ICM45686 connection:
 * P1-9  PB5 -> INT1
 * PB13 -> SCLK
 * PB14 -> MISO
 * PB15 -> MOSI
 * PB0  -> nCS
 */
#define BOARD_IMU_SPI_INSTANCE SPI2

#define BOARD_IMU_SCK_GPIO_PORT GPIOB
#define BOARD_IMU_SCK_GPIO_PIN GPIO_PIN_13
#define BOARD_IMU_SCK_GPIO_AF GPIO_AF5_SPI2

#define BOARD_IMU_MISO_GPIO_PORT GPIOB
#define BOARD_IMU_MISO_GPIO_PIN GPIO_PIN_14
#define BOARD_IMU_MISO_GPIO_AF GPIO_AF5_SPI2

#define BOARD_IMU_MOSI_GPIO_PORT GPIOB
#define BOARD_IMU_MOSI_GPIO_PIN GPIO_PIN_15
#define BOARD_IMU_MOSI_GPIO_AF GPIO_AF5_SPI2

#define BOARD_IMU_CS_GPIO_PORT GPIOB
#define BOARD_IMU_CS_GPIO_PIN GPIO_PIN_0

#define BOARD_IMU_INT1_GPIO_PORT GPIOB
#define BOARD_IMU_INT1_GPIO_PIN GPIO_PIN_5

#define BOARD_IMU_INT1_EXTI_IRQn EXTI9_5_IRQn
#define BOARD_IMU_INT1_IRQ_PRIORITY 5U
#define BOARD_IMU_INT1_IRQ_SUBPRIORITY 0U

#define BOARD_IMU_SPI_RX_DMA_INSTANCE DMA1_Stream0
#define BOARD_IMU_SPI_RX_DMA_REQUEST DMA_REQUEST_SPI2_RX
#define BOARD_IMU_SPI_RX_DMA_IRQn DMA1_Stream0_IRQn

#define BOARD_IMU_SPI_TX_DMA_INSTANCE DMA1_Stream1
#define BOARD_IMU_SPI_TX_DMA_REQUEST DMA_REQUEST_SPI2_TX

#define BOARD_U8_NOR_SPI_INSTANCE SPI1
#define BOARD_U8_NOR_SCK_GPIO_PORT GPIOB
#define BOARD_U8_NOR_SCK_GPIO_PIN GPIO_PIN_3
#define BOARD_U8_NOR_MISO_GPIO_PORT GPIOB
#define BOARD_U8_NOR_MISO_GPIO_PIN GPIO_PIN_4
#define BOARD_U8_NOR_MOSI_GPIO_PORT GPIOD
#define BOARD_U8_NOR_MOSI_GPIO_PIN GPIO_PIN_7
#define BOARD_U8_NOR_GPIO_AF GPIO_AF5_SPI1
#define BOARD_U8_NOR_CS_GPIO_PORT GPIOD
#define BOARD_U8_NOR_CS_GPIO_PIN GPIO_PIN_6
#define BOARD_IMU_SPI_TX_DMA_IRQn DMA1_Stream1_IRQn

#define BOARD_IMU_SPI_DMA_IRQ_PRIORITY 5U
#define BOARD_IMU_SPI_DMA_IRQ_SUBPRIORITY 0U




#endif
